# Generated by Django 4.2.3 on 2023-07-24 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0002_student_phone_alter_student_degree"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentsponsor",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sponsors",
                to="students.student",
            ),
        ),
    ]
