# Generated by Django 4.2.3 on 2023-07-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sponsors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sponsor",
            name="payment_type",
            field=models.CharField(
                choices=[("cash", "Cash"), ("card", "Card"), ("transfer", "Transfer")],
                default="card",
                max_length=8,
            ),
        ),
    ]
